  - name: disable redis
    ansible.builtin.command: dnf module disable redis -y

  - name: enable redis
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: enable redis
    ansible.builtin.package:
     name: redis
     state: installed

  - name: allow remote connections
    ansible.builtin.replace:
     path: /etc/redis/redis.conf
     regexp: "127.0.0.1"
     replace: "0.0.0.0"
  
  - name: disable protected-mode
    ansible.builtin.lineinfile:
     path: /etc/redis/redis.conf
     regexp: "protected-mode"
     line: protected-mode no

  - name: start redis
    ansible.builtin.service:
     name: redis
     state: started
     enabled: yes

