- name: import role app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name: import role python setup
  ansible.builtin.import_role:
   name: common
   tasks_from: python.yaml

- name: import role system setup
  ansible.builtin.import_role:
   name: common
   tasks_from: system-setup.yaml
