- name: roboshop user create
  ansible.builtin.user:
    name: roboshop
    comment: roboshop system user
    system: yes
    shell: /sbin/nologin
    home: /app

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: remove app from tmp directory
  ansible.builtin.file:
    path: /tmp/{{component}}.zip
    state: absent

- name: download {{component}} application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip
    dest: /tmp/{{component}}.zip

- name: extract {{component}} application to app directory
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes

- name: copy service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service
