
- name: "Start {{component}} service"
  ansible.builtin.service:
    name: "{{component}}"
    state: started
    enabled: yes

- name: daemon-reload
  ansible.builtin.systemd_service:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon-reload: yes
