- name: copy service file
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: /etc/systemd/system/{{component}}.service
  notify: daemon-reload

- name: "Start {{component}} service"
  ansible.builtin.service:
    name: "{{component}}"
    state: started
    enabled: yes

