
- name: import role app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name: import role nodejs setup
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs.yaml

- name: import role system setup
  ansible.builtin.import_role:
   name: common
   tasks_from: system-setup.yaml
